// internal/models/listing.go
// Pure Go types for the listings and listing_media tables.
// Derived from migrations/000003_create_listings.up.sql
// Derived from migrations/000004_create_listing_media.up.sql
// No DB code. No HTTP code. No business logic.

package models

import (
	"time"

	"github.com/google/uuid"
)

// ListingStatus maps exactly to the listing_status ENUM in PostgreSQL.
// Canonical vocabulary — ADR-005. Never use raw strings.
type ListingStatus string

const (
	StatusDraft         ListingStatus = "draft"
	StatusActive        ListingStatus = "active"
	StatusUnderContract ListingStatus = "under_contract"
	StatusSold          ListingStatus = "sold"
	StatusArchived      ListingStatus = "archived"
)

// PropertyType maps exactly to the property_type ENUM in PostgreSQL.
// Canonical vocabulary — ADR-005. Never use raw strings.
type PropertyType string

const (
	TypeLand       PropertyType = "land"
	TypeHouse      PropertyType = "house"
	TypeRancho     PropertyType = "rancho"
	TypeCommercial PropertyType = "commercial"
	TypeCabin      PropertyType = "cabin"
)

// Listing maps exactly to the listings table.
// search_vector is excluded — generated by PostgreSQL, never read directly.
type Listing struct {
	ID             uuid.UUID     `db:"id"              json:"id"`
	OwnerID        uuid.UUID     `db:"owner_id"        json:"owner_id"`
	Title          string        `db:"title"           json:"title"`
	Slug           string        `db:"slug"            json:"slug"`
	Description    *string       `db:"description"     json:"description,omitempty"`
	PropertyType   PropertyType  `db:"property_type"   json:"property_type"`
	Status         ListingStatus `db:"status"          json:"status"`
	PriceMXN       float64       `db:"price_mxn"       json:"price_mxn"`
	AreaM2         *float64      `db:"area_m2"         json:"area_m2,omitempty"`
	ConstructionM2 *float64      `db:"construction_m2" json:"construction_m2,omitempty"`
	Municipality   string        `db:"municipality"    json:"municipality"`
	Community      *string       `db:"community"       json:"community,omitempty"`
	Latitude       *float64      `db:"latitude"        json:"latitude,omitempty"`
	Longitude      *float64      `db:"longitude"       json:"longitude,omitempty"`
	IsFeatured     bool          `db:"is_featured"     json:"is_featured"`
	ViewCount      int           `db:"view_count"      json:"view_count"`
	CreatedAt      time.Time     `db:"created_at"      json:"created_at"`
	UpdatedAt      time.Time     `db:"updated_at"      json:"updated_at"`
	PublishedAt    *time.Time    `db:"published_at"    json:"published_at,omitempty"`

	// Joined from listing_media — not a DB column
	Media []ListingMedia `db:"-" json:"media,omitempty"`
}

// ListingMedia maps exactly to the listing_media table.
type ListingMedia struct {
	ID         uuid.UUID `db:"id"          json:"id"`
	ListingID  uuid.UUID `db:"listing_id"  json:"listing_id"`
	URL        string    `db:"url"         json:"url"`
	StorageKey string    `db:"storage_key" json:"-"` // internal only — never expose
	IsPrimary  bool      `db:"is_primary"  json:"is_primary"`
	SortOrder  int       `db:"sort_order"  json:"sort_order"`
	AltText    *string   `db:"alt_text"    json:"alt_text,omitempty"`
	CreatedAt  time.Time `db:"created_at"  json:"created_at"`
}

// IsPublic returns true if the listing is visible to the public.
func (l *Listing) IsPublic() bool {
	return l.Status == StatusActive
}

// IsOwnedBy returns true if the given user ID owns this listing.
func (l *Listing) IsOwnedBy(userID uuid.UUID) bool {
	return l.OwnerID == userID
}

// PrimaryPhoto returns the primary media item or nil if none exists.
// Returns first photo if none is marked primary.
func (l *Listing) PrimaryPhoto() *ListingMedia {
	for i := range l.Media {
		if l.Media[i].IsPrimary {
			return &l.Media[i]
		}
	}
	if len(l.Media) > 0 {
		return &l.Media[0]
	}
	return nil
}

// CanPublish returns true if the listing meets minimum data requirements.
// ADR-004: title, property_type, price_mxn, municipality are required.
// NOTE: photo presence is enforced by the service layer — not here.
// Media field may not be populated depending on how listing was fetched.
func (l *Listing) CanPublish() bool {
	return l.Title != "" &&
		l.PropertyType != "" &&
		l.PriceMXN > 0 &&
		l.Municipality != ""
}
